src/main/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path(f'{settings.ADMIN_URL}/', admin.site.urls),
    path('blog/', include('djtools.blog.urls')),
    path('services/', include('services.urls')),
    path('projects/', include('projects.urls')),
]

# On development serve media and static files using django
if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Django debug toolbar URLs
if settings.DEBUG_TOOLBAR:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/projects/urls.py
from django.urls import path

from . import views

app_name = 'projects'
urlpatterns = [
    path(
        route='',
        view=views.ProjectListView.as_view(),
        name='list',
    ),
    path(
        route='category/<slug:slug>/',
        view=views.ProjectCategoryDetailView.as_view(),
        name='category-detail',
    ),
    path(
        route='<slug:slug>/',
        view=views.ProjectDetailView.as_view(),
        name='detail',
    ),
]

src/services/urls.py
from django.urls import path

from . import views

app_name = 'services'
urlpatterns = [
    path('', views.ServiceListView.as_view(), name='list'),
    path('<slug:slug>/', views.ServiceDetailView.as_view(), name='detail'),
]

src/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

from blog import urls as blog_urls
from blog.views import PostListView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', PostListView.as_view(), name='home'),
    url(r'^blog/', include(blog_urls, namespace='blog')),
]


# Django debug toolbar URLs
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/main/models.py
from django.db import models
from django.utils.text import slugify

from . import managers


class OrderedModel(models.Model):
    title = models.CharField(
        max_length=255,
    )
    slug = models.SlugField(
        max_length=255,
    )
    description = models.TextField(
        blank=True,
    )

    order = models.PositiveIntegerField(
        default=0,
        db_index=True,
    )
    is_active = models.BooleanField(
        default=True,
        db_index=True,
    )
    is_featured = models.BooleanField(
        default=False,
        db_index=True,
    )

    objects = models.Manager()
    active = managers.ActiveManager()
    featured = managers.FeaturedManager()

    class Meta:
        abstract = True
        ordering = ['order']
        index_together = [
            ['is_active', 'order'],  # Service list
            ['is_active', 'is_featured', 'order'],  # Featured on home
        ]

    def __str__(self):
        return f"{self.title}"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

src/projects/models.py
from django.db import models
from django.utils.text import slugify

from main.models import OrderedModel

from . import utils


class Category(models.Model):
    name = models.CharField(
        max_length=255,
    )
    slug = models.SlugField(
        max_length=255,
    )
    order = models.PositiveIntegerField(
        default=0,
        db_index=True,
    )

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        ordering = ['order']

    def __str__(self):
        return f"{self.name}"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super().save(*args, **kwargs)


class Project(OrderedModel):
    thumbnail = models.ImageField(
        upload_to=utils.photo_upload_to,
        blank=True,
    )
    photo = models.ImageField(
        upload_to=utils.photo_upload_to,
        blank=True,
    )
    color = models.CharField(
        max_length=6,
        help_text='CSS RGB code'
    )
    categories = models.ManyToManyField(
        Category,
        related_name='projects',
        blank=True,
    )
    services = models.ManyToManyField(
        'services.Service',
        related_name='projects',
        blank=True,
    )

    def get_categories(self):
        return ' '.join(self.categories.values_list('slug', flat=True))

src/services/models.py
from django.db import models

from main.models import OrderedModel

from . import utils


class Service(OrderedModel):
    short_description = models.TextField()
    photo = models.ImageField(
        upload_to=utils.photo_upload_to,
        blank=True,
    )
    icon = models.CharField(
        max_length=255,
        blank=True,
        help_text='Font Awesome icon ID. https://fontawesome.com/icons'
    )

src/main/views.py
from django.views.generic.base import TemplateView

from djtools.blog.models import Post
from projects.models import Project
from services.models import Service


class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        return {
            'last_post': Post.get_last_post(),
            'featured_services': Service.featured.all()[:3],
            'featured_projects': Project.featured.all()[:3],
            **super().get_context_data(**kwargs)
        }

src/projects/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView

from .models import Project, Category


class ProjectListView(ListView):
    queryset = Project.active.all()
    category = None

    def get_context_data(self, **kwargs):
        return {
            **super().get_context_data(**kwargs),
            'categories': Category.objects.all(),
            'category': self.category,
        }


class ProjectDetailView(DetailView):
    queryset = Project.active.all()

    def get_context_data(self, **kwargs):
        return {
            **super().get_context_data(**kwargs),
            'without_header_img': True,
            'services': self.object.services.filter(is_active=True),
            'other_projects': self.queryset.filter(
                categories__in=self.object.categories.all(),
            ).exclude(
                id=self.object.id,
            ),
        }


class ProjectCategoryDetailView(ProjectListView):
    def dispatch(self, request, *args, **kwargs):
        self.category = get_object_or_404(
            Category,
            slug=self.kwargs['slug'],
        )
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return self.queryset.filter(categories=self.category)

src/services/views.py
from django.views.generic import ListView, DetailView

from .models import Service


class ServiceListView(ListView):
    queryset = Service.active.all()


class ServiceDetailView(DetailView):
    queryset = Service.active.all()

    def get_context_data(self, **kwargs):
        return {
            **super().get_context_data(**kwargs),
            'projects': self.object.projects.filter(is_active=True),
            'other_services': self.queryset.exclude(id=self.object.id),
        }

src/blog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="{{ AUTHOR_NAME }}">

        <title>Clean Blog - Start Bootstrap Theme</title>

        {# Bootstrap core CSS #}
        <link href="{% static "vendor/bootstrap/css/bootstrap.min.css"  %}" rel="stylesheet">

        {# Custom fonts for this template #}
        <link href="{% static "vendor/font-awesome/css/font-awesome.min.css"  %}" rel="stylesheet" type="text/css">
        <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

        {# Custom styles for this template #}
        <link href="{% static "css/clean-blog.min.css" %}" rel="stylesheet">
    </head>
    <body>

        {# Navigation #}
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="{% url 'home' %}">{{ SITE_NAME }}</a>
                {% comment %}
                    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                        Menu
                        <i class="fa fa-bars"></i>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarResponsive">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="index.html">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="about.html">About</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="post.html">Sample Post</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="contact.html">Contact</a>
                            </li>
                        </ul>
                    </div>
                {% endcomment %}
            </div>
        </nav>

        {% block content %}{% endblock content %}

        <hr>

        {# Footer #}
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-10 mx-auto">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="{{ GITHUB_URL }}" title="GitHub {{ AUTHOR_NAME }}" target="_blank" rel="nofollow">
                                    <span class="fa-stack fa-lg">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <p class="copyright text-muted">Copyright &copy; {{ SITE_NAME }} {% now "Y" %}</p>
                    </div>
                </div>
            </div>
        </footer>

        {# Bootstrap core JavaScript #}
        <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
        <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

        {# Custom scripts for this template #}
        <script src="{% static "js/clean-blog.min.js" %}"></script>
    </body>
</html>

src/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>{% block title %}{% endblock title %} | {{ SITE_NAME }}</title>
        <meta name="description" content="{% block description %}{% endblock description %}">
        <meta name="author" content="{{ AUTHOR_NAME }}">
        <meta name="googlebot" content="index, follow"/>
        <meta name="robots" content="index, follow"/>

        {% include "djtools/seo/google_analytics.html" %}

        <link rel="icon" href="{{ SITE_URL }}{% static "img/logos/favicon.ico" %}">

        <link href="{{ SITE_URL }}{% static "vendor/bootstrap/css/bootstrap.min.css"  %}" rel="stylesheet">
        <link href="{{ SITE_URL }}{% static "css/clean-blog.css" %}" rel="stylesheet">
        <link href="{{ SITE_URL }}{% static "vendor/font-awesome/css/font-awesome.min.css"  %}" rel="stylesheet" type="text/css">
        <link href="{{ SITE_URL }}{% static "css/custom.css" %}" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Fira+Sans:400,700" rel="stylesheet">

        {% block css %}{% endblock css %}
    </head>
    <body>
        {# Navigation #}
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="{% url 'home' %}" title="{{ SITE_NAME }}">
                    {% include "logo.html" %}
                </a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ SITE_URL }}{% url 'home' %}" title="Python Django freelance developer">Home</a>
                        </li>
                        {% if FLAGS.SERVICES_ENABLED %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ SITE_URL }}{% url 'services:list' %}" title="What is Django used for?">Services</a>
                            </li>
                        {% endif %}
                        {% if FLAGS.PROJECTS_ENABLED %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ SITE_URL }}{% url 'projects:list' %}" title="Python Django freelance projects">Projects</a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ SITE_URL }}{% url 'blog:list' %}" title="Toni Colom's blog">Blog</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        {# Page Header #}
        {% block page_header %}
            <header class="masthead"{% if not without_header_img %} style="background-image: url('{% block header_img %}{% endblock header_img %}')"{% endif %}>
                <div class="overlay"></div>
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 mx-auto">
                            <div class="{% block heading %}site-heading{% endblock heading %}">
                                <h1>{% block h1 %}{% endblock h1 %}</h1>
                                <h2 class="subheading">{% block h2 %}{% endblock h2 %}</h2>
                                {% block page_header_extra_content %}{% endblock page_header_extra_content %}
                            </div>
                        </div>
                    </div>
                </div>
            </header>
        {% endblock page_header %}

        {# Content #}
        {% block content %}{% endblock content %}
        <hr>

        {# Footer #}
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-10 mx-auto">
                        {% include "djtools/socialnetworks/social_networks.html" %}
                        <p class="copyright text-muted">Copyright &copy; {{ SITE_NAME }} {% now "Y" %}</p>
                    </div>
                </div>
            </div>
        </footer>

        {# Bootstrap core JavaScript #}
        <script src="{{ SITE_URL }}{% static "vendor/jquery/jquery.min.js" %}"></script>
        <script src="{{ SITE_URL }}{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

        <script>
            $(".linkbox").click(function() {
              window.location = $(this).find("a").attr("href");
              return false;
            });
        </script>

        {% block javascript %}{% endblock javascript %}
    </body>
</html>

src/templates/djtools/blog/post_detail.html
{% extends "base.html" %}
{% load humanize %}

{% block title %}{{ post.title }}{% endblock title %}
{% block description %}{{ post.subtitle }}{% endblock description %}

{% block heading %}post-heading{% endblock heading %}
{% block header_img %}{{ post.image.url }}{% endblock header_img %}
{% block h1 %}{{ post.title }}{% endblock h1 %}
{% block h2 %}{{ post.subtitle }}{% endblock h2 %}
{% block page_header_extra_content %}
    <span class="meta">Posted {{ post.created | naturalday}}</span>
{% endblock page_header_extra_content %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                {{ post.body | safe }}
            </div>
        </div>
    </div>
{% endblock content %}

src/templates/djtools/blog/post_list.html
{% extends "base.html" %}
{% load humanize static %}

{% block title %}Toni Colom's blog{% endblock title %}
{% block description %}Blog where you can find tutorials and solve problems about Django, Python and web development.{% endblock description %}

{% block header_img %}{% static "img/blog-bg.jpg" %}{% endblock header_img %}
{% block h1 %}Blog{% endblock h1 %}
{% block h2 %}Web development with Django and Python{% endblock h2 %}

{% block content %}
    {# Post List #}
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                {% for post in post_list %}
                    <div class="post-preview">
                        <a href="{{ SITE_URL }}{% url 'blog:detail' post.slug %}">
                            <h2 class="post-title">{{ post.title }}</h2>
                            <p class="post-subtitle">{{ post.subtitle }}</p>
                        </a>
                        <p class="post-meta">Posted {{ post.created | naturalday }}</p>
                    </div>
                    <hr>
                {% endfor %}

                {% comment %}
                    <!-- Pager -->
                    <div class="clearfix">
                        <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
                    </div>
                {% endcomment %}
            </div>
        </div>
    </div>
{% endblock content %}

src/templates/djtools/socialnetworks/social_networks.html
{% if social_networks %}
    <ul class="list-inline text-center">
        <li class="list-inline-item">
            <a href="mailto:toni@semicolom.com" title="Email {{ SITE_NAME }}" target="_blank" rel="nofollow">
                <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-envelope-o fa-stack-1x fa-inverse"></i>
                </span>
            </a>
        </li>
        {% for social_network in social_networks %}
            <li class="list-inline-item">
                <a href="{{ social_network.get_link }}" title="{{ social_network.get_name }} {{ SITE_NAME }}" target="_blank" rel="nofollow">
                    <span class="fa-stack fa-lg">
                        <i class="fa fa-circle fa-stack-2x"></i>
                        <i class="fa fa-{{ social_network.get_icon }} fa-stack-1x fa-inverse"></i>
                    </span>
                </a>
            </li>
        {% endfor %}
    </ul>
{% endif %}

src/templates/home.html
{% extends "base.html" %}
{% load humanize static %}

{% block title %}Toni Colom, Python Django freelance developer{% endblock title %}
{% block description %}APIs, apps and webs development with Python and Django{% endblock description %}

{% block header_img %}{% static "img/home-bg.jpg" %}{% endblock header_img %}
{% block h1 %}I develop<br><span class="typed"></span>{% endblock h1 %}

{% block content %}
    <div id="home" class="container">
        {% if FLAGS.SERVICES_ENABLED and featured_services %}
            <h2 class="text-center mb-5">Services</h2>
            <div class="row">
                {% for service in featured_services %}
                    <div class="col-sm-12 col-md-4 service">
                        <div class="service-icon">
                            <i class="fas fa-{{ service.icon }}"></i>
                        </div>
                        <a class="title" href="{{ SITE_URL }}{% url 'services:detail' service.slug %}" title="{{ service.title }}">{{ service.title }}</a>
                    </div>
                {% endfor %}
            </div>
            <br>
            <div class="row">
                <div class="col-offset-6 col-12 text-center">
                    <a class="btn btn-primary" href="{{ SITE_URL }}{% url 'services:list' %}" title="What is Django used for?">See more services</a>
                </div>
            </div>
            <br>
            <hr>
            <br>
        {% endif %}

        {% if FLAGS.PROJECTS_ENABLED and featured_projects %}
            <h2 class="text-center mb-5">Projects</h2>
            <div class="row">
                {% for project in featured_projects %}
                    <div class="col-sm-12 col-md-4 project">
                        {% if project.thumbnail %}
                            <img class="img-fluid mb-2" src="{{ project.thumbnail.url }}" alt="Logo {{ project.title }}">
                        {% endif %}
                        <a class="title" href="{{ SITE_URL }}{% url 'projects:detail' project.slug %}" title="{{ project.title }}">{{ project.title }}</a>
                    </div>
                {% endfor %}
            </div>
            <br>
            <div class="row">
                <div class="col-offset-6 col-12 text-center">
                    <a class="btn btn-primary" href="{{ SITE_URL }}{% url 'projects:list' %}" title="Python Django freelance projects">See more projects</a>
                </div>
            </div>
            <br>
            <hr>
            <br>
        {% endif %}

        {% if last_post %}
            <h2 class="text-center">Newest post</h2>
            <div class="row">
                <div class="col-12">
                    <div class="post-preview">
                        <a href="{{ SITE_URL }}{% url 'blog:detail' last_post.slug %}">
                            <h3 class="post-title">{{ last_post.title }}</h3>
                            <p class="post-subtitle">{{ last_post.subtitle }}</p>
                        </a>
                        <p class="post-meta">Posted {{ last_post.created | naturalday }}</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-offset-6 col-12 text-center">
                    <a class="btn btn-primary" href="{{ SITE_URL }}{% url 'blog:list' %}" title="Toni Colom's blog">Go to blog</a>
                </div>
            </div>
            <br>
        {% endif %}
     </div>
{% endblock content %}

{% block javascript %}
    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.9"></script>
    <script type="text/javascript">
        var options = {
            strings: ["APIs", "Apps", "Webs"],
            typeSpeed: 100,
            backSpeed: 100,
            backDelay: 1000,
            loop: true,
        }

        var typed = new Typed(".typed", options);
    </script>
{% endblock javascript %}

src/templates/projects/project_detail.html
{% extends "base.html" %}

{% block title %}{{ project.title }}, a project build with Python and Django{% endblock title %}
{% block description %}{{ project.title }}. {% for service in services %}{{ service.title }}, {% endfor %}. {% for category in project.categories.all %}{{ category.name }}, {% endfor %}{% endblock description %}

{% block css %}
    <style>
        header.masthead {
          background-color: #{{ project.color }};
        }
    </style>
{% endblock css %}

{% block h1 %}{{ project.title }}{% endblock h1 %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-8 mb-5">
                {% if project.photo %}
                    <img class="img-fluid mb-5" src="{{ project.photo.url }}" alt="{{ project.title }}, a project build with Python and Django">
                {% endif %}
                {{ project.description | safe }}
            </div>
            <div class="col-12 col-md-5">
                <div class="row">
                    {% if services %}
                        <div class="col-12 mb-5">
                            <h3 class="mb-4">Services</h3>
                            {% for service in services %}
                                <div class="mb-3">
                                    <i class="fa fa-{{ service.icon }}"></i>
                                    <a href="{% url 'services:detail' service.slug %}" title="{{ service.title }}">{{ service.title }}</a>
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                    {% if other_projects %}
                        <div class="col-12">
                            <h3 class="mb-4">Other projects</h3>
                            {% for other_project in other_projects %}
                                <div class="mb-3">
                                    <a href="{% url 'projects:detail' other_project.slug %}" title="{{ project.title }}, a project build with Python and Django">{{ other_project.title }}</a>
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-offset-6 col-12 text-center mb-5">
                <a class="btn btn-primary" href="mailto:toni@semicolom.com" title="Work with a Python Django freelance software engineer">Contact me</a>
            </div>
        </div>
    </div>
{% endblock content %}

src/templates/projects/project_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Python Django freelance{% if category %} {{ category.name }}{% endif %} projects{% endblock title %}
{% block description %}Are you looking for a freelance developer to build a{% if category %} {{ category.name }}{% endif %} project with Python or Django?{% endblock description %}

{% block header_img %}{% static "img/projects-bg.jpg" %}{% endblock header_img %}
{% block h1 %}Projects{% endblock h1 %}

{% block content %}
    <div id="projects" class="container">
        <div class="row filters mb-5">
            <div class="col-12 text-center">
                <a class="filter btn btn-light {% if not category %} active{% endif %}" href="{{ SITE_URL }}{% url 'projects:list' %}" title="Python Django freelance projects">All</a>
                {% for cat in categories %}
                    <a class="filter btn btn-light{% if cat == category %} active{% endif %}" href="{{ SITE_URL }}{% url 'projects:category-detail' cat.slug %}" title="Python Django freelance {{ cat.name }} projects">{{ cat.name }}</a>
                {% endfor %}
            </div>
        </div>
        <div class="row">
            {% for project in project_list %}
                <div class="col-12 col-md-6 col-lg-4 mb-4 project linkbox">
                    {% if project.thumbnail %}
                        <img class="img-fluid mb-2" src="{{ project.thumbnail.url }}" alt="Logo {{ project.title }}">
                    {% endif %}
                    <h2 class="title">
                        <a href="{{ SITE_URL }}{% url 'projects:detail' project.slug %}" title="{{ project.title }}, a project build with Python and Django">{{ project.title }}</a>
                    </h2>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

src/templates/services/service_detail.html
{% extends "base.html" %}

{% block title %}{{ service.title }}{% endblock title %}
{% block description %}{{ service.subtitle }}{% endblock description %}

{% block header_img %}{% if service.photo %}{{ service.photo.url }}{% endif %}{% endblock header_img %}
{% block h1 %}{{ service.title }}{% endblock h1 %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-8 mb-5">
                {{ service.description | safe }}
            </div>
            <div class="col-12 col-md-4 mb-5">
                <div class="row">
                    {% if projects %}
                        <div class="col-12 mb-5">
                            <h3 class="mb-4">Projects</h3>
                            {% for projects in projects %}
                                <div class="mb-3">
                                    <a href="{% url 'projects:detail' projects.slug %}" title="{{ project.title }}, a project build with Python and Django">{{ projects.title }}</a>
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                    {% if other_services %}
                        <div class="col-12">
                            <h3 class="mb-4">Other services</h3>
                            {% for other_service in other_services %}
                                <div class="mb-3">
                                    <i class="fa fa-{{ other_service.icon }}"></i>
                                    <a href="{% url 'services:detail' other_service.slug %}" title="{{ other_service.title }}">{{ other_service.title }}</a>
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-offset-6 col-12 text-center mb-5">
                <a class="btn btn-primary" href="mailto:toni@semicolom.com" title="Work with a Python Django freelance software engineer">Contact me</a>
            </div>
        </div>
    </div>
{% endblock content %}

src/templates/services/service_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}What is Django used for? Services provided by a freelance Python Django developer{% endblock title %}
{% block description %}{% for service in service_list %}{{ service.title }}{% if not forloop.last %}, {% endif %}{% endfor %}{% endblock description %}

{% block header_img %}{% static "img/services-bg.jpg" %}{% endblock header_img %}
{% block h1 %}Services{% endblock h1 %}

{% block content %}
    <div id="services" class="container">
        <div class="row">
            {% for service in service_list %}
                <div class="col-sm-12 col-md-6 col-lg-4 service linkbox">
                    <div class="service-icon">
                        <i class="fas fa-{{ service.icon }}"></i>
                    </div>
                    <h2 class="title"><a href="{{ SITE_URL }}{% url 'services:detail' service.slug %}">{{ service.title }}</a></h2>
                    <p>{{ service.short_description }}</p>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}